
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-18T18:37:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "594d3ae24e9faecc00549e0a1908b3434969c7d0",
 "version": "1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
