
# This file was generated by 'versioneer.py' (0.20.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-08T11:25:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "98eb875e22d864b02ee8e59c3c8e99a3ff1c2f34",
 "version": "0.16.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
