
# This file was generated by 'versioneer.py' (0.20.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-12T15:23:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "00aff2c7486dc1eec61a23e305d9aad71b0bfd09",
 "version": "0.16.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
