#!/bin/bash

# TODO: redo in Python with randomizing hierarchy and file siszes

d=$1
nfiles=$2

mkdir -p $d
cd $d
git init
git annex init
n=$nfiles
while [ $n -gt 0 ]; do
    echo "file$n" > $n
    n=$(($n-1))
done
git annex add * >/dev/null
git commit -m "added $nfiles files" >/dev/null

