#!/bin/bash

# take xx/yy git-annex repo and remap dropping number of 2nd level directories
# to see if with more collisions we get better performance

set -eu
cd $1

# First we will deal with .git/annex/objects
chmod +w -R .git/annex/objects/??
for d in .git/annex/objects/??/??; do
    # although it must be the same name, let's be uber careful
    td=$(echo $d | sed -e 's,objects/\(.\)\(.\)/\(.\).,objects/\1/\2\3,g')
    mkdir -p $td
    mv $d/* $td/
    rmdir ${d}
    #echo -n ,
done

# now remap all the symlinks
find -type l \
| while read f; do
   l=$(readlink "$f") 
   nl=$(echo $l | sed -e 's,objects/\(.\)\(.\)/\(.\).,objects/\1/\2\3,g')
   #nl=$(echo $l| sed -e 's,\(objects/../.\)./,\1/,g')
   rm $f; ln -s $nl $f
   # check if link is not broken
   [ -e $f ] || { echo BROKEN; exit 999; }
   #echo -n .
done
# make it again not writable
chmod -w -R .git/annex/objects/??

git gc --aggressive &>/dev/null
git repack -a -d -f --window=100 &>/dev/null
