#!/bin/bash
#emacs: -*- mode: shell-script; c-basic-offset: 4; tab-width: 4; indent-tabs-mode: t -*-
#ex: set sts=4 ts=4 sw=4 noet:
# ## ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
#
#   See COPYING file distributed along with the datalad package for the
#   copyright and license terms.
#
# ## ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
#
set -e
set -u

topdir=$(dirname `which $0 | xargs readlink -f `)/../..

cd $topdir

export DATALAD_TESTS_RUNCMDLINE=1
export PS4=+
grep -l DATALAD_TESTS_RUNCMDLINE docs/examples/* 2>/dev/null \
| while read t; do
    bash -x $t
done
