#!/bin/bash

set -eu

git clone https://github.com/GrahamDumpleton/wrapt /tmp/wrapt-dev
cd /tmp/wrapt-dev
## patch here if desired
git checkout develop
pip install -e .

# just install patched one from github
# pip install --upgrade https://github.com/yarikoptic/wrapt/archive/try1.zip
