#!/bin/bash
#
# A helper script which would take actual bisection script to be executed.
# It will first build git-annex using Singularity image, assuming that
# to bisect git-annex using a build environment in singularity image
#
set -eu
SINGULARITY_IMAGE="$1"
# The rest of cmdline is to execute
shift

if [ ! -e "$SINGULARITY_IMAGE" ]; then
    echo "I: trying to fetch singularity image with build env"
    singularity pull --name "$SINGULARITY_IMAGE" shub://datalad/datalad:git-annex-dev
fi

SINGULARITY_IMAGE=$(readlink -f "$SINGULARITY_IMAGE")
annex_gitver=$(git describe)
logfile=$PWD/.git/logs/git-annex-build-$annex_gitver.log

[ -e Annex.hs ]  # just to make sure that it is invoked in the correct location
echo "I: cleaning $PWD"
git clean -dfx
echo "I: building $annex_gitver"
if ! singularity exec -e $SINGULARITY_IMAGE make linuxstandalone 1>"$logfile" 2>&1; then
    echo "E: failed to build, can't test this one See $logfile"
    exit 125
fi
export PATH=$PWD/tmp/git-annex.linux/:$PATH

echo "I: running the script"
eval "$@"
