#!/bin/bash
#
set -u -e

function type () {
	echo "Not supported in scripts"
	exit 1
}
function key () {
	echo "Not supported in scripts"
	exit 1
}
function sleep () {
	# do nothing in a script
	:
}
function execute () {
	# do nothing in a script
	:
}
function say()
{
	printf "\n"
	printf "# $1\n" | fmt -w 72 --prefix '# '
}
function show () {
	# same as say
	printf "# $1\n" | fmt -w 72 --prefix '# '
}
function run () {
	printf "$1\n"
}
function run_expfail () {
	printf "$1 || true\n"
}


printf "#!/bin/bash\n"
show "This script was converted using cast2script from: $1"
cat << EOT
set -e -u
export GIT_PAGER=cat
EOT

. $1
