#!/usr/bin/python
#emacs: -*- mode: python; py-indent-offset: 4; tab-width: 4; indent-tabs-mode: nil -*-
#ex: set sts=4 ts=4 sw=4 noet:
"""Little helper to annotate logfile with difference between timestamps in consecutive lines"""

import sys
import re
from datetime import datetime

reg = re.compile('^\d{4}-\d{2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}')
prevt = None
maxl = 0

if len(sys.argv) <= 1:
    in_ = sys.stdin
else:
    in_ = open(sys.argv[1])
for l in in_:
    res = reg.search(l)
    dtstr = ''
    if res:
        #import pdb; pdb.set_trace()
        end = res.end()
        t = datetime.strptime(l[:end], '%Y-%m-%d %H:%M:%S,%f')
        if prevt is not None:
            dt = t - prevt
            ms = dt.microseconds // 1000
            dtstr = "." + ("%3d" % ms if ms else '   ')

            if dt.seconds:
                dtstr = "%2d" % (dt.seconds) + dtstr
            else:
                dtstr = "  " + dtstr

            maxl = max(maxl, len(dtstr))
            dtstr = '%%%ds' % maxl % dtstr
        prevt = t
        l = "%s %s" % (dtstr, l)
    sys.stdout.write(l)