#!/bin/sh

echo "The following people have contributed to DataLad:" > CONTRIBUTORS
echo >> CONTRIBUTORS

# note: some exclusions to clean up botched git author tags that got fixed in
# later commits, hopefully we'll be more careful about this in the future
git log --format='%aN' | sort | uniq | grep -E -v \
	'Mr.Nobody' | sort >> CONTRIBUTORS
