#!/usr/bin/python
# coding: utf-8

from __future__ import print_function
import sys
import boto
from boto.s3.key import Key
from boto.exception import S3ResponseError
from ConfigParser import SafeConfigParser

from six.moves.urllib.request import urlopen, Request
from six.moves.urllib.error import HTTPError

#bucket_prefix = 'datalad-test0-versioned/3versions-allversioned.txt'
#bucket_prefix = 'openfmri/ds001/demographics.txt'
#config_file = '/home/yoh/.s3cfg-datalad'

if len(sys.argv) != 3:
    sys.stderr.write("Format: %s s3cmd-config-file bucket/prefix" % sys.argv[0])

config_file, bucket_prefix = sys.argv[1:3]

if bucket_prefix.startswith('s3://'):
    bucket_prefix = bucket_prefix[5:]

config = SafeConfigParser(); config.read(config_file)

access_key = config.get('default', 'access_key')
secret_key = config.get('default', 'secret_key')


conn = boto.connect_s3(access_key, secret_key)
bucket_name, prefix = bucket_prefix.split('/', 1)
print("Connecting to bucket: %s" % bucket_name)

bucket = conn.get_bucket(bucket_name)
prefix_all_versions = list(bucket.list_versions(prefix))

max_length = max((len(e.name) for e in prefix_all_versions))
for e in prefix_all_versions:
    print(("%%%ds %%s" % max_length) % (e.name, e.last_modified), end=' ')
    if isinstance(e, Key):
        url = "http://{e.bucket.name}.s3.amazonaws.com/{e.name}?versionId={e.version_id}".format(e=e)
        try:
            _ = urlopen(Request(url))
            urlok = "OK"
        except HTTPError as err:
            urlok = "E: %s" % err.code
        try:
            acl = e.get_acl()
        except S3ResponseError as err:
            acl = err.message
        print("ver:%32s acl:%s url: %s [%s]" % (e.version_id, acl, url, urlok))
    else:
        print("del")

