name: Test old nose code

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-devel.txt
          pip install coverage datalad-installer nose
          datalad-installer --sudo ok -E /tmp/new.env \
            miniconda --batch \
            git-annex=8.20201007 -m conda
          . /tmp/new.env
          echo "PATH=$PATH" >> "$GITHUB_ENV"

      - name: Set up environment
        run: |
          git config --global user.email "test@github.land"
          git config --global user.name "GitHub Almighty"

          mkdir -p __testhome__

      - name: WTF
        run: datalad wtf

      - name: Test nose code
        run: |
          python -W error::DeprecationWarning:^datalad \
            -m nose --with-cov --cover-package datalad --logging-level=INFO \
            datalad.tests.test_tests_utils
          coverage report
          coverage xml
        working-directory: __testhome__

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: __testhome__
          fail_ci_if_error: false
